### PR TITLE
feat(Feature): Add a calendar on the feature flipping

### PR DESCRIPTION
**Pull request by MaximeLefrancois**

### CODE REVIEW

**Comment by elebescond** [comment]
DateTimeParseException when I'm trying to create a new feature 
```
2019-12-16T14:34:10.596 [vert.x-eventloop-thread-0] ERROR ai.tock.bot.admin.BotAdminVerticle - Text 'null' could not be parsed at index 0
java.time.format.DateTimeParseException: Text 'null' could not be parsed at index 0
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948)
	at java.base/java.time.ZonedDateTime.parse(ZonedDateTime.java:598)
	at java.base/java.time.ZonedDateTime.parse(ZonedDateTime.java:583)
	at ai.tock.bot.admin.BotAdminVerticle$configure$19.invoke(BotAdminVerticle.kt:264)
	at ai.tock.bot.admin.BotAdminVerticle$configure$19.invoke(BotAdminVerticle.kt:70)
	at ai.tock.shared.vertx.WebVerticle$blockingPost$1.invoke(WebVerticle.kt:339)
	at ai.tock.shared.vertx.WebVerticle$blockingPost$1.invoke(WebVerticle.kt:70)
	at ai.tock.shared.vertx.WebVerticle$executeBlocking$1.handle(WebVerticle.kt:557)
	at ai.tock.shared.vertx.WebVerticle$executeBlocking$1.handle(WebVerticle.kt:70)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by vsct-jburet** [comment]
@MaximeLefrancois  with this commit the features are still stored in memory: https://github.com/theopenconversationkit/tock/commit/17248bbb177094ba4bb11df3496fc76740354756 - If ok for you I merge ;)

**Comment by MaximeLefrancois** [comment]
@vsct-jburet: I'm ok ! you can merged! 👍

**Comment by vsct-jburet** [comment]
Merged. Thanks!

**Pull request closed without merging**
