### PR TITLE
#661 multi-pages subscription

### PR DESCRIPTION
**Pull request by vsct-jburet**

### CODE REVIEW

**Comment by gsoumier** [comment]
It would be cool to have at least an exemple or better a unit test

**Comment by vsct-jburet** [comment]
@gsoumier @NainJaune  @elebescond done. Please review :)

**Comment by vsct-jburet** [comment]
1/ and 2/ fixed. Also improve bot activation/deactivation methods

**Comment by vsct-jburet** [comment]
> When you can't find a connector associated with a pageId, we can throw a InvalidConfigurationException ?

I've just added an error log ;). Also fix a null postback error due to standby webhook

**Pull request closed without merging**
