### PR TITLE
[Tock Studio] Export and import of ia gen settings

### PR DESCRIPTION
**Pull request by rkuffer**
# Contributor summary 

Allow export and import (json format) of ia gen settings (Rag settings, Sentence generation settings, Observability settings, Vector DB settings) 

# AI Generated summary

This pull request introduces several significant updates to the observability and sentence generation settings components, focusing on adding export and import functionality for settings, confirming sensitive data export, and enhancing the user interface.

### Export and Import Functionality:

* [`bot/admin/web/src/app/configuration/observability-settings/observability-settings.component.html`](diffhunk://#diff-e60d96f19622181e247fb58596f9ea885c052ac58f785e270456dff7eaac70d2R6-R25): Added buttons for exporting and importing observability settings, along with corresponding modals for confirmation and file upload. [[1]](diffhunk://#diff-e60d96f19622181e247fb58596f9ea885c052ac58f785e270456dff7eaac70d2R6-R25) [[2]](diffhunk://#diff-e60d96f19622181e247fb58596f9ea885c052ac58f785e270456dff7eaac70d2R138-R250)
* [`bot/admin/web/src/app/configuration/sentence-generation-settings/sentence-generation-settings.component.html`](diffhunk://#diff-4ecd8104ddcbc066e83bf6e6870e068e6aec80a5d72cafcda0a6ddfca83f2aacR22-R41): Added buttons for exporting and importing sentence generation settings, along with corresponding modals for confirmation and file upload. [[1]](diffhunk://#diff-4ecd8104ddcbc066e83bf6e6870e068e6aec80a5d72cafcda0a6ddfca83f2aacR22-R41) [[2]](diffhunk://#diff-4ecd8104ddcbc066e83bf6e6870e068e6aec80a5d72cafcda0a6ddfca83f2aacR170-R280)

### Sensitive Data Export Confirmation:

* [`bot/admin/web/src/app/configuration/observability-settings/models/providers-configuration.ts`](diffhunk://#diff-9bc53b0219155e8d546ba23a5890d72ed336117a01be77bdec061b4326e1df3dR12): Added `confirmExport` property to `ProvidersConfigurationParam` interface and updated relevant configurations to include this property. [[1]](diffhunk://#diff-9bc53b0219155e8d546ba23a5890d72ed336117a01be77bdec061b4326e1df3dR12) [[2]](diffhunk://#diff-9bc53b0219155e8d546ba23a5890d72ed336117a01be77bdec061b4326e1df3dL26-R27)
* [`bot/admin/web/src/app/configuration/sentence-generation-settings/models/engines-configuration.ts`](diffhunk://#diff-6f4d5ea29746f299783aaf72e933c056b39c413d4d5afed615a042ad4255d460L44-R56): Added `confirmExport` property to relevant configurations to prompt confirmation before exporting sensitive data. [[1]](diffhunk://#diff-6f4d5ea29746f299783aaf72e933c056b39c413d4d5afed615a042ad4255d460L44-R56) [[2]](diffhunk://#diff-6f4d5ea29746f299783aaf72e933c056b39c413d4d5afed615a042ad4255d460L66-R66)

### Code Enhancements:

* [`bot/admin/web/src/app/configuration/observability-settings/observability-settings.component.ts`](diffhunk://#diff-745d1b973ddb2565cd6b57ca0d798b2d171fe5ad139fb410ead5bbed32b99af4L1-R19): Introduced methods for handling export and import operations, including `exportSettings`, `importSettings`, and confirmation modals. [[1]](diffhunk://#diff-745d1b973ddb2565cd6b57ca0d798b2d171fe5ad139fb410ead5bbed32b99af4L1-R19) [[2]](diffhunk://#diff-745d1b973ddb2565cd6b57ca0d798b2d171fe5ad139fb410ead5bbed32b99af4R46-R48) [[3]](diffhunk://#diff-745d1b973ddb2565cd6b57ca0d798b2d171fe5ad139fb410ead5bbed32b99af4R72-L64) [[4]](diffhunk://#diff-745d1b973ddb2565cd6b57ca0d798b2d171fe5ad139fb410ead5bbed32b99af4L139-R154) [[5]](diffhunk://#diff-745d1b973ddb2565cd6b57ca0d798b2d171fe5ad139fb410ead5bbed32b99af4R164-R170) [[6]](diffhunk://#diff-745d1b973ddb2565cd6b57ca0d798b2d171fe5ad139fb410ead5bbed32b99af4R218-R355)
* [`bot/admin/web/src/app/configuration/sentence-generation-settings/sentence-generation-settings.component.ts`](diffhunk://#diff-7f90ea5cb723f32bff2d1fea7b75eff6c3f95e9f2fff6aaba7aa0c2d8b9e2586L1-R1): Added similar methods for handling export and import operations.

### User Interface Improvements:

* [`bot/admin/web/src/app/configuration/observability-settings/observability-settings.component.scss`](diffhunk://#diff-e736440b4b084fa2cdcb40a096f0a53e30bb10906d4e694926f416ab053cbc02R1-R7): Added styles for `.grid-actions` to enhance the layout of action buttons.
* [`bot/admin/web/src/app/configuration/sentence-generation-settings/sentence-generation-settings.component.scss`](diffhunk://#diff-e736440b4b084fa2cdcb40a096f0a53e30bb10906d4e694926f416ab053cbc02R1-R7): Added styles for `.grid-actions` to enhance the layout of action buttons.

### CODE REVIEW

**Review by Benvii — APPROVED** [review]
Seems ok for me, even if I didn't look for all the change in details

**Comment by Benvii** [comment]
This PR as simple conflicts, could you solve them @rkuffer ? thanks in advance

**Comment by rkuffer** [comment]
> This PR has simple conflicts, could you solve them @rkuffer ? thanks in advance

Done

**Review by assouktim — APPROVED** [review]
Thanks !

**Pull request merged**
