### PR TITLE
[Fix] Prevent Poetry compilation problems in non-Linux environments

### PR DESCRIPTION
**Pull request by assouktim**

### CODE REVIEW

**Review by Benvii — APPROVED** [review]
lgtm

**Review by rkuffer — APPROVED** [review]

**Comment by Benvii** [comment]
@assouktim re-run poetry install to fix lock conflict

**Comment by assouktim** [comment]
This PR can wait a while, another PR is expected very soon to launch poetry on Windows.

**Comment by Benvii** [comment]
Can we close it now ? I think the issue is solved

**Pull request closed without merging**
