### PR TITLE
Breaking change : Proposal of verticle error handling

### PR DESCRIPTION
**Pull request by djowalker**
From the work of @henriSedjame : 
Here is a proposal :
- fixes https://github.com/theopenconversationkit/tock/issues/1470
- add a new way of creating verticle for developers with better HTTP errors handling exception with a Generic ToRestException for the implementation of WebVerticles
- Create functionnal verticle with parent and child Verticle (ex : according to AdminVerticle <-> BotAdminVerticle) to begin the decoupling of Verticles per business like asked in #1471

### CODE REVIEW

**Comment by djowalker** [comment]
Could be merged later, too much changes on error handling.

**Comment by vsct-jburet** [comment]
@djowalker I need to discuss with you further before merging this PR :)

**Comment by djowalker** [comment]
> @djowalker I need to discuss with you further before merging this PR :)

**Comment by djowalker** [comment]
@vsct-jburet yep we could discuss about it this week ?

**Comment by djowalker** [comment]
I think we have to avoid this evolution about Exception wich represents to much changes.

**Pull request closed without merging**
